export const getMockStudents = () => [
  { id: 1, 
    name: "Alice Smith", 
    email: "alice1@example.com", 
    course: "Math" 
  },
  { id: 2, 
    name: "Bob Johnson", 
    email: "bob2@example.com", 
    course: "Science" 
  },
  {
    id: 3,
    name: "Carol Williams",
    email: "carol3@example.com",
    course: "English",
  },
  { id: 4, 
    name: "David Brown", 
    email: "david4@example.com", 
    course: "Math" 
  },
  { id: 5, 
    name: "Eva Davis", 
    email: "eva5@example.com", 
    course: "Science" 
  },
  {
    id: 6,
    name: "Frank Miller",
    email: "frank6@example.com",
    course: "English",
  },
  { id: 7, 
    name: "Grace Wilson", 
    email: "grace7@example.com", 
    course: "Math" 
  },
  {
    id: 8,
    name: "Henry Moore",
    email: "henry8@example.com",
    course: "Science",
  },
  {
    id: 9,
    name: "Isabella Taylor",
    email: "isabella9@example.com",
    course: "English",
  },
  {
    id: 10,
    name: "Jack Anderson",
    email: "jack10@example.com",
    course: "Math",
  },
  {
    id: 11,
    name: "Katie Thomas",
    email: "katie11@example.com",
    course: "Science",
  },
  {
    id: 12,
    name: "Leo Jackson",
    email: "leo12@example.com",
    course: "English",
  },
  { id: 13, 
    name: "Mia White", 
    email: "mia13@example.com", 
    course: "Math" 
  },
  {
    id: 14,
    name: "Noah Harris",
    email: "noah14@example.com",
    course: "Science",
  },
  {
    id: 15,
    name: "Olivia Martin",
    email: "olivia15@example.com",
    course: "English",
  },
  {
    id: 16,
    name: "Paul Thompson",
    email: "paul16@example.com",
    course: "Math",
  },
  {
    id: 17,
    name: "Quinn Garcia",
    email: "quinn17@example.com",
    course: "Science",
  },
  {
    id: 18,
    name: "Ruby Martinez",
    email: "ruby18@example.com",
    course: "English",
  },
  { id: 19, 
    name: "Sam Robinson", 
    email: "sam19@example.com", 
    course: "Math" 
  },
  {
    id: 20,
    name: "Tina Clark",
    email: "tina20@example.com",
    course: "Science",
  },
  {
    id: 21,
    name: "Uma Rodriguez",
    email: "uma21@example.com",
    course: "English",
  },
  {
    id: 22,
    name: "Victor Lewis",
    email: "victor22@example.com",
    course: "Math",
  },
  {
    id: 23,
    name: "Wendy Lee",
    email: "wendy23@example.com",
    course: "Science",
  },
  {
    id: 24,
    name: "Xander Walker",
    email: "xander24@example.com",
    course: "English",
  },
  { id: 25, 
    name: "Yara Hall", 
    email: "yara25@example.com", 
    course: "Math" 
  },
  {
    id: 26,
    name: "Zack Allen",
    email: "zack26@example.com",
    course: "Science",
  },
  { id: 27, 
    name: "Amy Young", 
    email: "amy27@example.com", 
    course: "English" 
  },
  {
    id: 28,
    name: "Brian Hernandez",
    email: "brian28@example.com",
    course: "Math",
  },
  {
    id: 29,
    name: "Cathy King",
    email: "cathy29@example.com",
    course: "Science",
  },
  {
    id: 30,
    name: "Derek Wright",
    email: "derek30@example.com",
    course: "English",
  },
  { id: 31, name: "Ella Lopez", email: "ella31@example.com", course: "Math" },
  { id: 32, name: "Finn Hill", email: "finn32@example.com", course: "Science" },
  {
    id: 33,
    name: "Gina Scott",
    email: "gina33@example.com",
    course: "English",
  },
  { id: 34, name: "Hank Green", email: "hank34@example.com", course: "Math" },
  { id: 35, name: "Ivy Adams", email: "ivy35@example.com", course: "Science" },
  {
    id: 36,
    name: "Jake Baker",
    email: "jake36@example.com",
    course: "English",
  },
  { id: 37, name: "Lily Nelson", email: "lily37@example.com", course: "Math" },
  { id: 38, name: "Max Carter", email: "max38@example.com", course: "Science" },
  {
    id: 39,
    name: "Nina Mitchell",
    email: "nina39@example.com",
    course: "English",
  },
  { id: 40, name: "Oscar Perez", email: "oscar40@example.com", course: "Math" },
  {
    id: 41,
    name: "Penny Roberts",
    email: "penny41@example.com",
    course: "Science",
  },
  {
    id: 42,
    name: "Quincy Turner",
    email: "quincy42@example.com",
    course: "English",
  },
  {
    id: 43,
    name: "Rita Phillips",
    email: "rita43@example.com",
    course: "Math",
  },
  {
    id: 44,
    name: "Steve Campbell",
    email: "steve44@example.com",
    course: "Science",
  },
  {
    id: 45,
    name: "Tara Parker",
    email: "tara45@example.com",
    course: "English",
  },
  { id: 46, name: "Umar Evans", email: "umar46@example.com", course: "Math" },
  {
    id: 47,
    name: "Violet Edwards",
    email: "violet47@example.com",
    course: "Science",
  },
  {
    id: 48,
    name: "Walt Collins",
    email: "walt48@example.com",
    course: "English",
  },
  {
    id: 49,
    name: "Xenia Stewart",
    email: "xenia49@example.com",
    course: "Math",
  },
  {
    id: 50,
    name: "Yusuf Sanchez",
    email: "yusuf50@example.com",
    course: "Science",
  },
];
